export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const USER_LOGIN = "USER_LOGIN";
export const USER_FAIL_LOGIN = "USER_FAIL_LOGIN"



export const FEED_POST = "FEED_POST";
export const FEED_POST_FAIL = "FEED_POST_FAIL";

